/**
 * Textos del flujo de compra: checkout, pago, respuesta de Payphone, seguimiento
 * y "mis pedidos". Las notas que definió el cliente (envío, factura,
 * transferencia, WhatsApp) siguen en `site.checkout`; esto es solo interfaz.
 */
export const checkoutCopy = {
  page: {
    eyebrow: 'Finalizar compra',
    title: 'Completa tu pedido',
    lead: 'Cuatro pasos cortos. No necesitas crear una cuenta para comprar.',
    emptyTitle: 'No hay nada que pagar todavía',
    emptyText: 'Tu carrito está vacío. Elige tus productos y vuelve para terminar la compra.',
    backToCart: 'Volver al carrito',
    formLabel: 'Datos del pedido',
  },

  steps: {
    contact: { title: 'Tus datos', lead: 'Para avisarte cómo va tu pedido.' },
    shipping: { title: 'Envío', lead: 'A dónde llevamos tu café.' },
    billing: { title: 'Facturación', lead: 'A nombre de quién sale la factura.' },
    payment: { title: 'Pago', lead: 'Elige cómo quieres pagar.' },
  },

  fields: {
    name: 'Nombre y apellido',
    email: 'Correo',
    phone: 'Teléfono o celular',
    province: 'Provincia',
    provincePlaceholder: 'Elige tu provincia',
    city: 'Ciudad',
    address: 'Dirección',
    addressHint: 'Calle principal, número y calle secundaria.',
    reference: 'Referencia',
    referenceHint: 'Color de la casa, local cercano o cómo llegar.',
    idType: 'Tipo de identificación',
    idNumber: 'Número de identificación',
    billingName: 'Nombre o razón social',
    billingAddress: 'Dirección de facturación',
    billingEmail: 'Correo para la factura',
    billingPhone: 'Teléfono para la factura',
    optional: 'opcional',
  },

  idTypes: {
    cedula: 'Cédula',
    ruc: 'RUC',
    pasaporte: 'Pasaporte',
    consumidor_final: 'Consumidor final',
  },

  billing: {
    sameAsContact: 'Usar mis datos de contacto',
    sameAsContactHint: 'La factura sale con tu nombre, correo, teléfono y dirección de envío.',
    consumerNote: 'La factura sale como consumidor final, sin tus datos personales.',
  },

  errors: {
    name: 'Escribe tu nombre y apellido',
    email: 'Escribe un correo válido',
    phone: 'Escribe un teléfono válido, solo con números',
    province: 'Elige la provincia de envío',
    city: 'Escribe la ciudad de envío',
    address: 'Escribe la dirección de envío',
    idNumber: 'Escribe el número de identificación',
    cedula: 'La cédula no es válida. Revisa los 10 dígitos',
    ruc: 'El RUC no es válido. Revisa los 13 dígitos',
    pasaporte: 'Escribe un pasaporte válido, de 5 a 20 caracteres',
    billingName: 'Escribe el nombre o razón social para la factura',
    billingAddress: 'Escribe la dirección para la factura',
    billingEmail: 'Escribe un correo válido para la factura',
    billingPhone: 'Escribe un teléfono válido para la factura',
    summary: 'Revisa los campos marcados antes de continuar',
  },

  location: {
    title: 'Punto de entrega',
    lead: 'Si estás en el lugar de entrega, comparte tu ubicación para que el repartidor llegue sin perderse.',
    use: 'Usar mi ubicación actual',
    locating: 'Buscando tu ubicación…',
    saved: 'Ubicación guardada',
    viewMap: 'Ver en Google Maps',
    remove: 'Quitar ubicación',
    denied:
      'No tenemos permiso para ver tu ubicación. Puedes activarlo en tu navegador o continuar solo con la dirección.',
    unsupported: 'Tu navegador no permite compartir la ubicación. Continúa con la dirección.',
    failed: 'No pudimos obtener tu ubicación. Inténtalo otra vez o continúa con la dirección.',
  },

  summary: {
    title: 'Resumen del pedido',
    items: 'Productos',
    subtotal: 'Subtotal de productos',
    shipping: 'Envío',
    shippingTo: 'Envío a',
    total: 'Total a pagar',
    totalPartial: 'Total sin envío',
    chooseProvince: 'Elige tu provincia',
    calculating: 'Calculando…',
    byWhatsapp: 'Se confirma por WhatsApp',
    quoteError: 'No se pudo calcular',
    quoteErrorText: 'No pudimos calcular el envío. Revisa tu conexión.',
    retryQuote: 'Calcular de nuevo',
    qty: 'Cantidad',
    edit: 'Editar carrito',
  },

  payment: {
    methodLabel: 'Forma de pago',
    card: 'Tarjeta de crédito o débito',
    cardHint: 'Pago seguro con Payphone. Se acredita al instante.',
    transfer: 'Transferencia bancaria',
    transferHint: 'Te mostramos las cuentas y subes la foto del comprobante.',
    payCard: 'Pagar con tarjeta',
    payTransfer: 'Confirmar pedido',
    sending: 'Creando tu pedido…',
    createError: 'No pudimos crear tu pedido. Inténtalo de nuevo en un momento.',
    waitQuote: 'Elige tu provincia para calcular el envío y habilitar el pago.',
    noRateTitle: 'Este pedido se cierra por WhatsApp',
    or: 'o si prefieres',
  },

  whatsapp: {
    shipTo: 'Envío a',
    customer: 'A nombre de',
  },

  payphone: {
    eyebrow: 'Pago con tarjeta',
    title: 'Paga tu pedido',
    order: 'Pedido',
    loading: 'Cargando el formulario de pago…',
    secure: 'Tus datos de tarjeta los procesa Payphone. Nosotros no los vemos ni los guardamos.',
    timeLeft: 'Tiempo para pagar',
    expiredTitle: 'El formulario de pago venció',
    expiredText:
      'Por seguridad, el formulario dura 10 minutos. Genera un intento nuevo para pagar; no se te ha cobrado nada.',
    newAttempt: 'Generar un intento nuevo',
    generating: 'Generando…',
    errorTitle: 'No pudimos cargar el formulario de pago',
    errorText: 'Revisa tu conexión e inténtalo de nuevo. Tu pedido no se ha cobrado.',
    retry: 'Volver a cargar',
    back: 'Cambiar datos o forma de pago',
  },

  transfer: {
    eyebrow: 'Pago por transferencia',
    title: 'Tu pedido está reservado',
    lead: 'Transfiere el total exacto a una de estas cuentas y sube la foto del comprobante.',
    order: 'Pedido',
    total: 'Total exacto a transferir',
    accountsTitle: 'Cuentas bancarias',
    bank: 'Banco',
    accountType: 'Tipo de cuenta',
    number: 'Número de cuenta',
    holder: 'Titular',
    idNumber: 'Cédula o RUC',
    copy: 'Copiar',
    copied: 'Copiado',
    copyNumber: 'Copiar número de cuenta',
    copyFailed: 'No se pudo copiar. Selecciona el número y cópialo a mano.',
    track: 'Ver el estado de mi pedido',
    emailSent: 'También te enviamos estos datos a tu correo.',
  },

  proof: {
    title: 'Comprobante de transferencia',
    lead: 'Sube una foto o captura de pantalla del comprobante. Solo imágenes, máximo 4 MB.',
    choose: 'Elegir imagen',
    change: 'Cambiar imagen',
    upload: 'Enviar comprobante',
    uploading: 'Enviando…',
    previewAlt: 'Vista previa del comprobante elegido',
    currentAlt: 'Comprobante enviado',
    notImage: 'El comprobante debe ser una imagen (foto o captura de pantalla), no un PDF.',
    tooBig: 'La imagen pesa más de 4 MB. Toma una captura de pantalla o reduce su tamaño.',
    uploaded: 'Comprobante recibido. Tu pedido queda por verificar.',
    sentTitle: 'Comprobante recibido',
    replace: 'Enviar otro comprobante',
  },

  response: {
    title: 'Resultado del pago',
    confirmingTitle: 'Estamos confirmando tu pago',
    confirmingText: 'No cierres ni recargues esta página. Toma solo unos segundos.',
    approvedEyebrow: 'Pago aprobado',
    approvedTitle: 'Gracias por tu compra',
    approvedText: 'Recibimos tu pago y ya estamos preparando tu pedido. Te enviamos el detalle a',
    orderNumber: 'Número de pedido',
    totalPaid: 'Total pagado',
    track: 'Ver el estado de mi pedido',
    rejectedTitle: 'El pago no se completó',
    rejectedText:
      'El pago fue cancelado o rechazado y no se hizo ningún cobro. Tu carrito sigue intacto: puedes intentarlo de nuevo.',
    tryAgain: 'Intentar de nuevo',
    pendingTitle: 'Todavía no podemos confirmar tu pago',
    errorTitle: 'No pudimos confirmar tu pago',
    errorText: 'Puede ser un problema de conexión. Vuelve a intentarlo: no se cobra dos veces.',
    retry: 'Reintentar la confirmación',
    retrying: 'Confirmando…',
    missingTitle: 'No hay ningún pago que confirmar',
    missingText:
      'Esta página se abre sola al terminar un pago con tarjeta. Si ya pagaste, revisa el correo que te enviamos.',
    help: 'Necesito ayuda con mi pago',
    helpMessage: 'Hola, necesito ayuda con el pago de mi pedido en Café Malacatos.',
  },

  tracking: {
    eyebrow: 'Seguimiento',
    title: 'Pedido',
    askTitle: 'Confirma tu correo',
    askText: 'Para proteger tus datos, escribe el correo con el que hiciste el pedido',
    emailLabel: 'Correo del pedido',
    submit: 'Ver mi pedido',
    loading: 'Buscando tu pedido…',
    notFoundTitle: 'No encontramos ese pedido',
    notFoundText:
      'Revisa que el número y el correo sean los mismos de tu compra. Si el problema sigue, escríbenos.',
    errorTitle: 'No pudimos cargar tu pedido',
    placedOn: 'Realizado el',
    statusTitle: 'Estado del pedido',
    itemsTitle: 'Productos',
    shippingTitle: 'Dirección de envío',
    billingTitle: 'Facturación',
    paymentTitle: 'Forma de pago',
    trackingNoteTitle: 'Datos del envío',
    invoiceIssued: 'Factura emitida',
    invoicePending: 'Factura por emitir',
    viewMap: 'Ver punto en Google Maps',
    helpMessage: 'Hola, tengo una consulta sobre mi pedido',
    help: 'Consultar por WhatsApp',
    payPendingCard:
      'Este pedido con tarjeta no se llegó a pagar. Si quieres completarlo, vuelve a hacer la compra desde la tienda.',
  },

  status: {
    label: 'Estado',
    pending: { label: 'Pendiente de pago', step: 'Pedido recibido' },
    awaiting_verification: { label: 'Por verificar', step: 'Comprobante por verificar' },
    paid: { label: 'Pagado', step: 'Pago confirmado' },
    shipped: { label: 'Enviado', step: 'Pedido enviado' },
    delivered: { label: 'Entregado', step: 'Pedido entregado' },
    cancelled: { label: 'Cancelado', step: 'Pedido cancelado' },
    cancelledText: 'Este pedido fue cancelado. Si crees que es un error, escríbenos.',
    current: 'Estado actual',
    done: 'Completado',
    upcoming: 'Pendiente',
  },

  myOrders: {
    title: 'Mis pedidos',
    loading: 'Cargando tus pedidos…',
    emptyTitle: 'Todavía no tienes pedidos',
    emptyText: 'Cuando compres con tu cuenta, tus pedidos aparecerán aquí.',
    errorText: 'No pudimos cargar tus pedidos.',
    view: 'Ver seguimiento',
    items: 'productos',
    item: 'producto',
  },
} as const

export type CheckoutErrorKey = keyof typeof checkoutCopy.errors
